name: Integration Tests

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  packages: read

env:
  DEBUG: true
  LOG_DRIVER: file

jobs:
  MySQL:
    runs-on: ubuntu-22.04
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: kanboard
          MYSQL_DATABASE: kanboard
          MYSQL_USER: kanboard
          MYSQL_PASSWORD: kanboard
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: ./.github/actions/setup-php
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup document root
        run: |
          sudo rm -rf /var/www/html
          sudo cp -R $GITHUB_WORKSPACE /var/www/html
          sudo cp tests/configs/config.mysql.php /var/www/html/config.php
          sudo chown -R www-data:www-data /var/www/html/data
      - name: Integration tests with MySQL
        run: ./vendor/bin/phpunit -c tests/integration.mysql.xml
        env:
          DB_HOSTNAME: 127.0.0.1
          DB_USERNAME: kanboard
          DB_PASSWORD: kanboard
          DB_NAME: kanboard