name: Unit Tests

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: false
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: false

permissions:
  contents: read
  packages: read

env:
  DEBUG: true
  LOG_DRIVER: file

jobs:
  MySQL:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - uses: ./.github/actions/setup-php
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Unit tests with MySQL
        run: ./vendor/bin/phpunit -c tests/units.mysql.xml
        env:
          DB_HOSTNAME: 127.0.0.1
          DB_USERNAME: kanboard
          DB_PASSWORD: kanboard
          DB_NAME: kanboard